# Generated by Django 5.0.1 on 2024-04-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jd1',
            fields=[
                ('job_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('job_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Jd',
        ),
    ]
