# Generated by Django 5.0.1 on 2024-04-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_jd1_delete_jd'),
    ]

    operations = [
        migrations.CreateModel(
            name='match_per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('jd', models.TextField()),
                ('mp', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
