# Generated by Django 5.0.1 on 2024-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_match_per_alter_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_per',
            name='mp',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
