# Generated by Django 5.0.1 on 2024-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_match_per_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_per',
            name='mp',
            field=models.IntegerField(default=0),
        ),
    ]
