# Generated by Django 5.0.1 on 2024-04-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_match_per_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_per',
            name='resume',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(),
        ),
    ]
