# Generated by Django 5.0.1 on 2024-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_match_per_resume_alter_resume_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_per',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
