# Generated by Django 5.0.1 on 2024-05-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_match_per_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_per',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.jd1'),
            preserve_default=False,
        ),
    ]
