# Generated by Django 5.0.1 on 2024-05-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_match_per_jd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='match_per',
            new_name='Match_per1',
        ),
    ]
