# Generated by Django 5.0.1 on 2024-05-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_match_per_match_per1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('mp', models.IntegerField(default=0)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.jd1')),
            ],
        ),
        migrations.DeleteModel(
            name='Match_per1',
        ),
    ]
