# Generated by Django 5.0.1 on 2024-05-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_match_pro_delete_match_per1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_pro',
            old_name='job_id',
            new_name='jobid',
        ),
    ]
