# Generated by Django 5.0.1 on 2024-05-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_job_id_match_pro_jobid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_pro',
            old_name='jobid',
            new_name='job_id',
        ),
    ]
