# Generated by Django 5.0.1 on 2024-05-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_jobid_match_pro_job_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match_pro',
            new_name='Match_per',
        ),
    ]
