# Generated by Django 5.0.1 on 2024-05-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_match_pro_match_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
