# Generated by Django 5.0.1 on 2024-05-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_admins_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jd1',
            name='department',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jd1',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
