# Generated by Django 5.0.1 on 2024-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_jd1_department_jd1_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='id',
        ),
        migrations.AlterField(
            model_name='employe',
            name='eid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
