# Generated by Django 5.0.1 on 2024-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_employe_groups_employe_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='employe',
            name='eid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
