# Generated by Django 5.0.1 on 2024-06-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employe',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_login',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
